const elections = {
  "2024-primary": {
    year: 2024,
    date: "8/6/24",
    label: "2024 Primary",
    races: {
      0: "Turnout",
      3: "US Senator: Democratic",
      4: "US Senator: Republican",
      9: "US Rep. 12th District: Democratic",
      10: "US Rep. 12th District: Republican",
      11: "US Rep. 13th District: Democratic",
      12: "US Rep. 13th District: Republican",
      13: "State Rep. 1st District: Democratic",
      14: "State Rep. 1st District: Republican",
      17: "State Rep. 3rd District: Democratic",
      18: "State Rep. 3rd District: Republican",
      19: "State Rep. 4th District: Democratic",
      21: "State Rep. 5th District: Democraticn",
      22: "State Rep. 5th District: Republican",
      25: "State Rep. 7th District: Democratic",
      26: "State Rep. 7th District: Republican",
      27: "State Rep. 8th District: Democratic",
      28: "State Rep. 8th District: Republican",
      29: "State Rep. 9th District: Democratic",
      30: "State Rep. 9th District: Republican",
      31: "State Rep. 10th District: Democratic",
      32: "State Rep. 10th District: Republican",
      33: "State Rep. 11th District: Democratic",
      34: "State Rep. 11th District: Republican",
      35: "State Rep. 12th District: Democratic",
      36: "State Rep. 12th District: Republican",
      43: "State Rep. 16th District: Democratic",
      44: "State Rep. 16th District: Republican",
      45: "State Rep. 17th District: Democratic",
      46: "State Rep. 17th District: Republican",
      66: "Prosecuting Attorney: Democratic",
      68: "Sheriff: Democratic",
      69: "Sheriff: Republican",
      70: "Clerk: Democratic",
      72: "Register of Deeds: Democratic",
      73: "Register of Deeds: Republican",
      74: "County Commissioner, 1st District: Democratic",
      76: "County Commissioner, 2nd District: Democratic",
      78: "County Commissioner, 3rd District: Democratic",
      80: "County Commissioner, 4th District: Democratic",
      82: "County Commissioner, 5th District: Democratic",
      84: "County Commissioner, 6th District: Democratic",
      86: "County Commissioner, 7th District: Democratic",
      178: "Treasurer: Democratic",
      182: "Judge of 3rd Circuit Court, Non-Incumbent",
      188: "Proposition A - Auditor Selection",
      189: "Proposition P - Parks Millage Renewal",
      1907: "Proposal L - Libraries Millage Renewal",
    },
  },
  "2024-general": {
    year: 2024,
    label: "2024 General",
    date: "11/5/24",
    races: {
      0: "Turnout",
      1: "Straight Party Ticket",
      2: "Electors of President",
      3: "US Senator",
      6: "US Rep. 12th District",
      7: "US Rep. 13th District",
      8: "State Rep. 1st District",
      10: "State Rep. 3rd District",
      11: "State Rep. 4th District",
      12: "State Rep. 5th District",
      13: "State Rep. 7th District",
      14: "State Rep. 8th District",
      15: "State Rep. 9th District",
      16: "State Rep. 10th District",
      17: "State Rep. 11th District",
      18: "State Rep. 12th District",
      20: "State Rep. 16th District",
      21: "State Rep. 17th District",
      31: "Prosecuting Attorney",
      32: "Sheriff",
      33: "Clerk",
      34: "Treasurer",
      35: "Register of Deeds",
      41: "County Commissioner, 1st District",
      42: "County Commissioner, 2nd District",
      43: "County Commissioner, 3rd District",
      44: "County Commissioner, 4th District",
      45: "County Commissioner, 5th District",
      46: "County Commissioner, 6th District",
      47: "County Commissioner, 7th District",
      1172: "Justice of the Supreme Court, Non-Incumbent",
      1165: "Justice of the Supreme Court, Incumbent",
      94: "Judge of 1st District Court of Appeals, Incumbent",
      95: "Judge of 3rd Circuit Court, Incumbent",
      1193: "Judge of 3rd Circuit Court, Non-Incumbent",
      96: "Judge of 3rd Circuit Court, Incumbent, Partial",
      97: "Judge of Probate Court, Incumbent",
      124: "Board of Trustees, 1st District Wayne County Community College",
      125: "Board of Trustees, 3rd District Wayne County Community College",
      136: "Board Member, Detroit Public Schools Community District",
      1150: "Detroit School District - Proposal S Operating Millage",
      1160: "Wayne RESA - Renewal of Regional Enhancement Millage Proposal",
      1161: "Member of the State Board of Education",
      1162: "Regent of the University of Michigan",
      1163: "Trustee of Michigan State University",
      1164: "Governor of Wayne State University",
      98: "Judge of Probate Court, Non-Incumbent",
      108: "Judge of 36th District Court, Incumbent",
      109: "Judge of 36th District Court, Non-Incumbent",
      1169: "Judge of 36th District Court, Incumbent, Partial",
    },
  },
}

export default elections
